### ISSUE TITLE
how do the arrow keys work?

### ISSUE THREAD

**Issue by jergas** [andrew-wilkes/3dsnake#1]
hi! I cloned 3dsnake and compiled it locally. I tried it for while, and, while I can see that each arrow key alternates between 2 directions, I couldn't figure out which 2 well enough to play. would you please add a description of what the arrow keys do?
thanks!

**Comment by andrew-wilkes** [comment]
Hi, it was tricky to decide on how to handle movement control. From my tutorial notes I wrote: "We will do this looking at the scene rather than trough the eyes of the Snake. We have to move in the direction that seems most natural for the key pressed in relation to the current direction of travel of the Snake." The problem when coding this is that the snake head may be upside down etc. So if you treat the snake head like a pilot's cabin then it would be very confusing because of changes in orientation whilst looking at the snake as an observer of the scene.
